<?php
/**
 * @category Qsolutions
 * @package Q_Admin
 * @author Michał Jóźwiak <michalj@qsolutionsstudio.com>
 *
 * @var $this Q_Admin_Block_Adminhtml_Trend_Form
 */
?>

<script>
    function changeChart() {
        new Ajax.Request('<?php echo Mage::helper("adminhtml")->getUrl("*/*/ajaxBlock", array('_current' => true)) ?>', {
            method: 'post',
            parameters: {
                trend_from: $('trend_from').value,
                trend_to: $('trend_to').value,
                sku: $('trend_sku').value,
                period: $('trend_period').value,
                isAjax: 'true',
                form_key: FORM_KEY
            },
            onSuccess: function(transport) {
                var response = transport.responseText.evalJSON() || "no response text";

                $('trend_chart').replace(response.graph);
                $('trend_chart_table').replace(response.table);
            },
            onFailure: function() {
                alert('Cannot load data')
            }
        });
    }
</script>

<div class="content-header">
    <h3 class="head-dashboard"><?php echo $this->__('Product Trend') ?></h3>
    <div class="form-buttons">
        <button type="submit" form="trend_data_range" value="Submit">Show chart</button>
    </div>
</div>
<div class="dashboard-container q-diagram-container">
    <div class="switcher a-left" style="padding:5px 10px;">
        <form id="bestseller_data_range" method="post" style="padding-right: 50px;">
            <label for="trend_from"> <?php echo $this->__('From') ?>:</label>
            <?php echo $this->getChildHtml('html_calendar') ?>
            <img style="" title="Select Date" class="v-middle" id="trend_from_trig" alt="" src="<?php echo $this->getSkinUrl("images/grid-cal.gif");?> "/>
            <input type="text" name="trend_from" id="trend_from" class="input-text" style="width:110px !important;" value="<?php echo date('Y-m-d', strtotime("-1 month")) ?>" required/>

            <label for="trend_to"> <?php echo $this->__('To') ?>:</label>
            <?php echo $this->getChildHtml('html_calendar') ?>
            <img style="" title="Select Date" class="v-middle" id="trend_to_trig" alt="" src="<?php echo $this->getSkinUrl("images/grid-cal.gif");?> "/>
            <input type="text" name="trend_to" id="trend_to" class="input-text" style="width:110px !important;" value="<?php echo date('Y-m-d') ?>"/>

            <label for="trend_period"> <?php echo $this->__('Period') ?>:</label>
            <select name="period" id="trend_period" style="width: 80px">
                <?php foreach ($this->helper('q_admin/adminhtml_bestsellers_data')->getPeriod() as $value => $label):?>
                    <option value="<?php echo $value ?>" <?php if($this->getRequest()->getParam('period')==$value): ?> selected="selected"<?php endif; ?>><?php echo $label ?></option>
                <?php endforeach; ?>
            </select>

            <label for="trend_sku"><?php echo $this->__('Sku') ?>:</label>
            <input type="text" name="trend_sku" id="trend_sku" class="input-text" style="width:110px !important;" value=""/>
        </form>
    </div>

    <div class="q-diagram-chart" style="padding:5px 10px;">
        <div class="entry-edit-head"><h4><?php echo $this->__('Diagram') ?></h4></div>
        <?php echo $this->getChildHtml('trend_graph') ?>
    </div>
    <div class="q-diagram-table" style="padding:5px 10px;">
        <div class="entry-edit-head"><h4><?php echo $this->getTitle() ?></h4></div>
        <fieldset class="np"><?php echo $this->getChildHtml('trend_table') ?></fieldset>
    </div>
</div>


<script>
    jQuery("button").click(function(event){
        event.preventDefault();
        changeChart();
    });

    Calendar.setup({
        inputField : 'trend_from',
        ifFormat : '%Y-%m-%d',
        showsTime: false,
        button : 'trend_from_trig',
        singleClick : true,
    });
    Calendar.setup({
        inputField : 'trend_to',
        ifFormat : '%Y-%m-%d',
        showsTime: false,
        button : 'trend_to_trig',
        singleClick : true,
    });

    google.charts.load('current', {'packages':['corechart', 'line']});
</script>