<?php
/**
 * @category Qsolutions
 * @package Q_Admin
 * @author Michał Jóźwiak <michalj@qsolutionsstudio.com>
 *
 * @var $this Q_Admin_Block_Adminhtml_Bestsellers_Tab_Graph
 */?>

<?php
$columns = $this->getChartColumns();
$rows    = $this->getChartRows();

$countedColumns = count($columns);
$colors         = $this->getDiagramHelper()->colorManipulator($countedColumns);
?>

<div class="box" id="bestsellers_chart">
        <?php if (!empty($columns)): ?>
    <div class="only-chart" id="bestsellers_canvas"></div>
        <?php elseif (empty($columns)): ?>
    <p class="a-center"><?php echo $this->__('No data found') ?></p>
        <?php endif; ?>
</div>

<script>

    var element = document.getElementById("bestsellers_canvas");

    if (element !== null) {
        google.charts.setOnLoadCallback(bestsellersChart);
    }
    function bestsellersChart() {

        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Period');
        <?php foreach ($columns as $column) {
            echo sprintf("data.addColumn('number', '%s');", $column);
         } ?>

        data.addRows([
            <?php foreach ($rows as $row) {
                echo sprintf("[{v: '%s', f: '%s'}, %s],", $row['period'], $row['period'], $row['sales_in_period']);
            } ?>
            ]);

        var options = {
            chartArea:{left:'7%',top:20,width:'75%',height:'85%'},
            colors: <?php echo $colors ?>,
        };

        var chart = new google.visualization.ColumnChart(
            document.getElementById('bestsellers_canvas'));

        chart.draw(data, options);
    }
</script>