<?php
/**
 * @category Qsolutions
 * @package Q_Admin
 * @author Michał Jóźwiak <michalj@qsolutionsstudio.com>
 *
 * @var $this Q_Admin_Block_Adminhtml_Shipping_Tab_Table
 */
?>

<?php
$shippingCollection = $this->getDataAdjustedToShow();
?>
<div class="box" id="shipping_table">
    <table class="chartTable" >
        <tr>
            <th><?php echo $this->__('Shipping Method Title') ?></th>
            <th><?php echo $this->__('Shipping Qty') ?></th>
            <th><?php echo $this->__('Shipping Method uses in %') ?></th>
        </tr>
        <?php foreach ($shippingCollection as $shipping): ?>
            <tr>
                <td><?php echo $shipping->getShippingMethodTitle(); ?></td>
                <td><?php echo $shipping->getShippingQtyInPeriod(); ?></td>
                <td><?php echo $shipping->getShippingMethodUsesInPercent(); ?>%</td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>