<?php
/**
 * @category Qsolutions
 * @package Q_Admin
 * @author Michał Jóźwiak <michalj@qsolutionsstudio.com>
 *
 * @var $this Q_Admin_Block_Adminhtml_Hours_Tab_Graph
 */
?>

<?php
$chartCollection = $this->getCollectionPrepareToShow();
$chartItems      = $chartCollection->getItems();
?>

<div class="box" id="hours_chart">
    <?php if (!empty($chartItems)): ?>
        <div class="only-chart" id="hours_canvas"></div>
    <?php elseif (empty($chartItems)): ?>
        <p class="a-center"><?php echo $this->__('No data found') ?></p>
    <?php endif; ?>
</div>

<script>
    var element = document.getElementById("hours_canvas");

    if (element !== null) {
        google.charts.setOnLoadCallback(salesInHoursChart);
    }

    function salesInHoursChart() {

        var data = new google.visualization.DataTable();
        data.addColumn('timeofday', 'Time of Day');
        data.addColumn('number', 'Sales');

        data.addRows([
            <?php
             foreach ($chartCollection as $hoursSale) {
                $hourToChart = $hoursSale->getHourAdjustedToShow();
                $hourToLabel = $hoursSale->getHourLabel();
                $itemsQty    = $hoursSale->getItemsQty();

                echo "[{v: [" . $hourToChart . "], f: '" . $hourToLabel . "'}, " . $itemsQty . "],";
             }
             ?>
        ]);

        var options = {
            chartArea:{left:'7%',top:20,width:'80%',height:'85%'},
            colors: ['#ea5b0c'],
            hAxis: {
                format: 'H:mm',
                viewWindow: {
                    min: [00, 00, 00],
                    max: [23, 59, 59]
                }
            },

        };

        var chart = new google.visualization.ColumnChart(
            document.getElementById('hours_canvas'));

        chart.draw(data, options);
    }
</script>