<?php
/**
 * @category Qsolutions
 * @package Q_Admin
 * @author Michał Jóźwiak <michalj@qsolutionsstudio.com>
 *
 * @var $this Q_Admin_Block_Adminhtml_Lifetime_Lifetime
 */
?>
<?php
$firstOrder = $this->getFirstSalesDate();
$firstSale = date('Y-m-d', strtotime($firstOrder['created_at']));
?>
<div class="content-header">
    <h3 class="head-dashboard"><?php echo $this->__('Sales Lifetime Statistics') ?></h3>
</div>
<div class="dashboard-container q-diagram-container">
    <div class="q-diagram-chart" style="padding:5px 10px;">
        <div class="entry-edit-head"><h4><?php echo $this->__('Customer Group') ?></h4></div>
        <?php echo $this->getChild('salescustomer_graph')->setFrom($firstSale)->toHtml() ?>
    </div>
    <div class="q-diagram-chart" style="padding:5px 10px;">
        <div class="entry-edit-head"><h4><?php echo $this->__('Customer Registered/Guests') ?></h4></div>
        <?php echo $this->getChild('customer_graph')->setFrom($firstSale)->toHtml() ?>
    </div>
    <div class="q-diagram-chart" style="padding:5px 10px;">
        <div class="entry-edit-head"><h4><?php echo $this->__('Sales By Payment Method') ?></h4></div>
        <?php echo $this->getChild('payment_graph')->setFrom($firstSale)->toHtml() ?>
    </div>
    <div class="q-diagram-chart" style="padding:5px 10px;">
        <div class="entry-edit-head"><h4><?php echo $this->__('Sales By Shipping Method') ?></h4></div>
        <?php echo $this->getChild('shipping_graph')->setFrom($firstSale)->toHtml() ?>
    </div>
    <div class="q-diagram-chart" style="padding:5px 10px;">
        <div class="entry-edit-head"><h4><?php echo $this->__('Sales by Hours') ?></h4></div>
        <?php echo $this->getChild('hours_graph')->setFrom($firstSale)->toHtml() ?>
    </div>
    <div class="q-diagram-chart" style="padding:5px 10px;">
        <div class="entry-edit-head"><h4><?php echo $this->__('Conversion Advanced Report (sales/views)') ?></h4></div>
        <?php echo $this->getChild('conversion')->setFrom($firstSale)->toHtml() ?>
    </div>
</div>

<script>
    google.charts.load('current', {'packages':['corechart', 'line']});
</script>