<?php
/**
 * @category Qsolutions
 * @package Q_Admin
 * @author Michał Jóźwiak <michalj@qsolutionsstudio.com>
 *
 * @var $this Q_Admin_Block_Adminhtml_Customer_Form
 */
?>

<script>
    function changeChart() {
        new Ajax.Request('<?php echo Mage::helper("adminhtml")->getUrl("*/*/ajaxBlock", array('_current' => true)) ?>', {
            method: 'post',
            parameters: {
                customer_from: $('customer_from').value,
                customer_to: $('customer_to').value,
                isAjax: 'true',
                form_key: FORM_KEY
            },
            onSuccess: function(transport) {
                var response = transport.responseText.evalJSON() || "no response text";

                $('customer_chart').replace(response.graph);
            },
            onFailure: function() {
                alert('Cannot load data')
            }
        });
    }
</script>

<div class="content-header">
    <h3 class="head-dashboard"><?php echo $this->__('Customer Group Sales') ?></h3>
    <div class="form-buttons">
        <button type="submit" form="customer_data_range" value="Submit">Show chart</button>
    </div>
</div>
<div class="dashboard-container q-diagram-container">
    <div class="switcher a-left" style="padding:5px 10px;">
        <form id="bestseller_data_range" method="post" style="padding-right: 50px;">
            <?php echo $this->__('From') ?>:
            <?php echo $this->getChildHtml('html_calendar') ?>
            <img style="" title="Select Date" class="v-middle" id="customer_from_trig" alt="" src="<?php echo $this->getSkinUrl("images/grid-cal.gif");?> "/>
            <input type="text" name="customer_from"class="input-text" style="width:110px !important;" id="customer_from" value="<?php echo date('Y-m-01') ?>" required/>

            <?php echo $this->__('To') ?>:
            <?php echo $this->getChildHtml('html_calendar') ?>
            <img style="" title="Select Date" class="v-middle" id="customer_to_trig" alt="" src="<?php echo $this->getSkinUrl("images/grid-cal.gif");?> "/>
            <input type="text" name="customer_to" id="customer_to" class="input-text" style="width:110px !important;" value="<?php echo date('Y-m-d') ?>"/>
        </form>
    </div>

    <div class="q-diagram-customer-chart" style="padding:5px 10px;">
        <div class="entry-edit-head"><h4><?php echo $this->__('Diagram') ?></h4></div>
        <?php echo $this->getChildHtml('customer_graph') ?>
    </div>
</div>

<script>
    jQuery("button").click(function(event){
        event.preventDefault();
        changeChart();
    });

    Calendar.setup({
        inputField : 'customer_from',
        ifFormat : '%Y-%m-%d',
        showsTime: false,
        button : 'customer_from_trig',
        singleClick : true,
    });
    Calendar.setup({
        inputField : 'customer_to',
        ifFormat : '%Y-%m-%d',
        showsTime: false,
        button : 'customer_to_trig',
        singleClick : true,
    });

    google.charts.load('current', {'packages':['corechart']});
</script>