<?php
/**
 * @category Qsolutions
 * @package Q_Admin
 * @author Michał Jóźwiak <michalj@qsolutionsstudio.com>
 *
 * @var $this Q_Admin_Block_Adminhtml_Payment_Tab_Table
 */
?>

<?php
$paymentCollection = $this->getDataAdjustedToShow();
?>
<div class="box" id="payment_table">
    <table class="chartTable" >
        <tr>
            <th><?php echo $this->__('Payment Method Title') ?></th>
            <th><?php echo $this->__('Payment Qty') ?></th>
            <th><?php echo $this->__('Payment Method uses in %') ?></th>
        </tr>
        <?php foreach ($paymentCollection as $payment): ?>
            <tr>
                <td><?php echo $payment->getPaymentMethodTitle(); ?></td>
                <td><?php echo $payment->getPaymentQtyInPeriod(); ?></td>
                <td><?php echo $payment->getPaymentMethodUsesInPercent(); ?>%</td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>