<?php
/**
 * @category Qsolutions
 * @package Q_Admin
 * @author Michał Jóźwiak <michalj@qsolutionsstudio.com>
 *
 * @var $this Q_Admin_Block_Adminhtml_Conversion_Tab_Graph
 */
?>

<?php
$conversionCollection = $this->getChartData();
$conversionItems      = $conversionCollection->getItems();
?>
<div class="box" id="conversion_chart">
    <?php if (!empty($conversionItems)): ?>
        <div class="only-chart" id="conversion_canvas"></div>
    <?php elseif (empty($conversionItems)) : ?>
        <p class="a-center"><?php echo $this->__('No data found') ?></p>
    <?php endif; ?>
</div>

<script>
    var element = document.getElementById("conversion_canvas");

    if (element !== null) {
        google.charts.setOnLoadCallback(ConversionDrawChart);
    }

    function ConversionDrawChart() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Day');
        data.addColumn('number', "Sales Trend");

        data.addRows([
            <?php foreach ($conversionCollection as $conversion) : ?>
            ['<?php echo $conversion->getMonth() ?>', <?php echo $conversion->getConversion() ?>],
            <?php endforeach; ?>
        ]);

        var options = {
            chartArea:{left:'7%',top:20,width:'80%',height:'85%'},
            curveType: 'function',
            colors: ['#ea5b0c'],
            pointSize: 7,
            hAxis: {showTextEvery: 2},
            vAxis: {
                format: "percent"
            },
        };

        var chart = new google.visualization.LineChart(document.getElementById('conversion_canvas'));
        chart.draw(data, options);    }
</script>