<?php
/**
 * @category Qsolutions
 * @package Q_Admin
 * @author Michał Jóźwiak <michalj@qsolutionsstudio.com>
 *
 * @var $this Q_Admin_Block_Adminhtml_Hours_Tab_Table
 */
?>

<?php
$salesByHour = $this->getCountedCollection();
?>
<div class="box" id="hours_table">
    <table class="chartTable" >
        <tr>
            <th><?php echo $this->__('Hour') ?></th>
            <th><?php echo $this->__('Items Ordered') ?></th>
            <th><?php echo $this->__('Amount') ?></th>

        </tr>
        <?php foreach ($salesByHour as $sales): ?>
            <tr>
                <td><?php echo $sales->getHoursValue(); ?></td>
                <td><?php echo $sales->getItemsQty(); ?></td>
                <td><?php echo Mage::helper('core')->currency($sales->getTotalAmount(), true, false) ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>