<?php
/**
 * @category Qsolutions
 * @package Q_Admin
 * @author Michał Jóźwiak <michalj@qsolutionsstudio.com>
 *
 * @var $this Q_Admin_Block_Adminhtml_Country_Tab_Graph
 */
?>

<?php
$chartData = $this->getChartData();
?>

<div class="box" id="country_sales_chart">
    <?php if (!empty($chartData)): ?>
        <div class="only-chart" id="canvas_country"></div>
    <?php elseif (empty($chartData)): ?>
        <p class="a-center"><?php echo $this->__('No data found') ?></p>
    <?php endif; ?>
</div>

<script>
    var element = document.getElementById("canvas_country");

    if (element !== null) {
        google.charts.setOnLoadCallback(drawRegionsMap);
    }

    function drawRegionsMap() {

        var data = google.visualization.arrayToDataTable([
            ['Country', 'Sales'],
            <?php
            foreach ($chartData as $country) {
                $country_label = $country['country_label'];
                $country_items_qty = $country['country_items_qty'];

                echo '[' . Mage::helper('core')->jsonEncode($country_label) . ', ' . Mage::helper('core')->jsonEncode($country_items_qty) . '],';
            }
            ?>
        ]);

        var options = {
            colorAxis: {colors: ['#f7f7f7', '#ea5b0c']},
            datalessRegionColor: 'white',
        };

        var chart = new google.visualization.GeoChart(document.getElementById('canvas_country'));

        chart.draw(data, options);
    }
</script>

