<?php
/**
 * @category Qsolutions
 * @package Q_Admin
 * @author Michał Jóźwiak <michalj@qsolutionsstudio.com>
 *
 * @var $this Q_Admin_Block_Adminhtml_Shipping_Tab_Graph
 */
?>

<?php
$shippingCollection = $this->getDataAdjustedToShow();
$shippingItems      = $shippingCollection->getItems();

$countedShipping = count($shippingCollection);
$colors          = $this->getDiagramHelper()->colorManipulator($countedShipping);
?>

<div class="box" id="shipping_chart">
    <?php if (!empty($shippingItems)): ?>
        <div class="only-chart" id="shipping_canvas"></div>
    <?php elseif (empty($shippingItems)) : ?>
        <p class="a-center"><?php echo $this->__('No data found') ?></p>
    <?php endif; ?>
</div>

<script>
    var element = document.getElementById("shipping_canvas");

    if (element !== null) {
        google.charts.setOnLoadCallback(shippingDrawChart);
    }

    function shippingDrawChart() {
        var data = google.visualization.arrayToDataTable([
            ['Sales by shipping method', 'Shipping Qty'],
            <?php
            foreach ($shippingCollection as $shipping) {
                $shipping_method_title  = $shipping->getShippingMethodTitle();
                $shipping_qty_in_period = $shipping->getShippingQtyInPeriod();

                echo "['" . $shipping_method_title . "', " . $shipping_qty_in_period . '],';
            }
            ?>
        ]);

        var options = {
            chartArea: {top:'5%', bottom: '5%'},
            colors: <?php echo $colors ?>,
            pieHole: 0.4,
        };

        var chart = new google.visualization.PieChart(document.getElementById('shipping_canvas'));

        chart.draw(data, options);
    }
</script>