<?php
/**
 * @category Qsolutions
 * @package Q_Admin
 * @author Michał Jóźwiak <michalj@qsolutionsstudio.com>
 *
 * @var $this Q_Admin_Block_Adminhtml_Bestsellers_Form
 */ ?>

<script>
    function changeChart() {
        new Ajax.Request('<?php echo Mage::helper("adminhtml")->getUrl("*/*/ajaxBlock", array('_current' => true)) ?>', {
            method: 'post',
            parameters: {
                period: $('period_of_orders').value,
                limit: $('qty_of_orders').value,
                bestseller_from: $('bestseller_from').value,
                bestseller_to: $('bestseller_to').value,
                isAjax: 'true',
                form_key: FORM_KEY
            },
            onSuccess: function(transport) {
                var response = transport.responseText.evalJSON() || "no response text";

                $('bestsellers_chart').replace(response.graph);
                $('chart_table').replace(response.table);
            },
            onFailure: function() {
                alert('Cannot load data')
            }
        });
    }
</script>

<div class="content-header">
    <h3 class="head-dashboard"><?php echo $this->__('Bestsellers Advanced Report') ?></h3>
    <div class="form-buttons">
        <button type="submit" form="bestseller_data_range" value="Submit">Show chart</button>
    </div>
</div>
<div class="dashboard-container q-diagram-container">
    <div class="switcher a-left" style="padding:5px 10px;">
        <form id="bestseller_data_range" method="post" style="padding-right: 50px;">
            <label><?php echo $this->__('From') ?>:</label>
            <?php echo $this->getChildHtml('html_calendar') ?>
            <img style="" title="Select Date" class="v-middle" id="bestseller_from_trig" alt="" src="<?php echo $this->getSkinUrl("images/grid-cal.gif");?> "/>
            <input type="text" name="bestseller_from" id="bestseller_from" class="input-text" style="width:110px !important;" value="<?php echo date('Y-m-01') ?>" required/>

            <label><?php echo $this->__('To') ?>:</label>
            <?php echo $this->getChildHtml('html_calendar') ?>
            <img style="" title="Select Date" class="v-middle" id="bestseller_to_trig" alt="" src="<?php echo $this->getSkinUrl("images/grid-cal.gif");?> "/>
            <input type="text" name="bestseller_to" id="bestseller_to" class="input-text" style="width:110px !important;" value="<?php echo date('Y-m-d') ?>"/>
            <label><?php echo $this->__('Qty of orders') ?>:</label>
            <select name="qty" id="qty_of_orders" style="width: 50px">
                <?php foreach ($this->helper('q_chart/adminhtml_bestsellers_data')->getQty() as $value):?>
                        <option value="<?php echo $value ?>" <?php if($this->getRequest()->getParam('limit')==$value): ?> selected="selected"<?php endif; ?>><?php echo $value ?></option>
                <?php endforeach; ?>
            </select>
            <label><?php echo $this->__('Period') ?>:</label>
            <select name="period" id="period_of_orders" style="width: 80px">
                <?php foreach ($this->helper('q_chart/adminhtml_bestsellers_data')->getPeriod() as $value => $label):?>
                    <option value="<?php echo $value ?>" <?php if($this->getRequest()->getParam('period')==$value): ?> selected="selected"<?php endif; ?>><?php echo $label ?></option>
                <?php endforeach; ?>
            </select>
        </form>
    </div>

    <div class="q-diagram-chart" style="padding:5px 10px;">
        <div class="entry-edit-head"><h4><?php echo $this->__('Diagram') ?></h4></div>
        <?php echo $this->getChildHtml('bestseller_graph') ?>
    </div>
    <div class="q-diagram-table" style="padding:5px 10px;">
        <div class="entry-edit-head"><h4><?php echo $this->getTitle() ?></h4></div>
        <fieldset class="np"><?php echo $this->getChildHtml('bestseller_table') ?></fieldset>
    </div>
</div>


<script>
    jQuery("button").click(function(event){
        event.preventDefault();
        changeChart();
    });

    Calendar.setup({
        inputField : 'bestseller_from',
        ifFormat : '%Y-%m-%d',
        showsTime: false,
        button : 'bestseller_from_trig',
        singleClick : true,
    });
    Calendar.setup({
        inputField : 'bestseller_to',
        ifFormat : '%Y-%m-%d',
        showsTime: false,
        button : 'bestseller_to_trig',
        singleClick : true,
    });

    google.charts.load('current', {packages: ['corechart', 'bar']});
</script>