<?php
/**
 * @category Qsolutions
 * @package Q_Admin
 * @author Michał Jóźwiak <michalj@qsolutionsstudio.com>
 *
 * @var $this Q_Admin_Block_Adminhtml_Hours_Form
 */
?>

<script>
    function changeChart() {
        new Ajax.Request('<?php echo Mage::helper("adminhtml")->getUrl("*/*/ajaxBlock", array('_current' => true)) ?>', {
            method: 'post',
            parameters: {
                hours_from: $('hours_from').value,
                hours_to: $('hours_to').value,
                isAjax: 'true',
                form_key: FORM_KEY
            },
            onSuccess: function(transport) {
                var response = transport.responseText.evalJSON() || "no response text";

                $('hours_chart').replace(response.graph);
                $('hours_table').replace(response.table);
            },
            onFailure: function() {
                alert('Cannot load data')
            }
        });
    }
</script>

<div class="content-header">
    <h3 class="head-dashboard"><?php echo $this->__('Sales by Hours') ?></h3>
    <div class="form-buttons">
        <button type="submit" form="hours_data_range" value="Submit">Show chart</button>
    </div>
</div>
<div class="dashboard-container q-diagram-container">
    <div class="switcher a-left" style="padding:5px 10px;">
        <form id="bestseller_data_range" method="post" style="padding-right: 50px;">
            <?php echo $this->__('From') ?>:
            <?php echo $this->getChildHtml('html_calendar') ?>
            <img style="" title="Select Date" class="v-middle" id="hours_from_trig" alt="" src="<?php echo $this->getSkinUrl("images/grid-cal.gif");?> "/>
            <input type="text" name="hours_from"class="input-text" style="width:110px !important;" id="hours_from" value="<?php echo date('Y-m-01') ?>" required/>

            <?php echo $this->__('To') ?>:
            <?php echo $this->getChildHtml('html_calendar') ?>
            <img style="" title="Select Date" class="v-middle" id="hours_to_trig" alt="" src="<?php echo $this->getSkinUrl("images/grid-cal.gif");?> "/>
            <input type="text" name="hours_to" id="hours_to" class="input-text" style="width:110px !important;" value="<?php echo date('Y-m-d') ?>"/>
        </form>
    </div>

    <div class="q-diagram-chart" style="padding:5px 10px;">
        <div class="entry-edit-head"><h4><?php echo $this->__('Diagram') ?></h4></div>
        <?php echo $this->getChildHtml('hours_graph') ?>
    </div>
    <div class="q-diagram-table" style="padding:5px 10px;">
        <div class="entry-edit-head"><h4><?php echo $this->getTitle() ?></h4></div>
        <fieldset class="np"><?php echo $this->getChildHtml('hours_table') ?></fieldset>
    </div>
</div>

<script>
    jQuery("button").click(function(event){
        event.preventDefault();
        changeChart();
    });

    Calendar.setup({
        inputField : 'hours_from',
        ifFormat : '%Y-%m-%d',
        showsTime: false,
        button : 'hours_from_trig',
        singleClick : true,
    });
    Calendar.setup({
        inputField : 'hours_to',
        ifFormat : '%Y-%m-%d',
        showsTime: false,
        button : 'hours_to_trig',
        singleClick : true,
    });

    google.charts.load('current', {packages: ['corechart', 'bar']});
</script>