<?php
/**
 * @category Qsolutions
 * @package Q_Admin
 * @author Michał Jóźwiak <michalj@qsolutionsstudio.com>
 *
 * @var $this Q_Admin_Block_Adminhtml_Customergroup_Tab_Graph
 */
?>

<?php
$customerGroupCollection = $this->customerGroupSalesInPercent();
$customerItems           = $customerGroupCollection->getItems();

$countedCustomerGroup = count($customerGroupCollection);
$colors               = $this->getDiagramHelper()->colorManipulator($countedCustomerGroup);
?>

<div class="box" id="customer_group_chart">
    <?php if (!empty($customerItems)): ?>
        <div class="only-chart" id="canvas"></div>
    <?php elseif (empty($customerItems)) : ?>
        <p class="a-center"><?php echo $this->__('No data found') ?></p>
    <?php endif; ?>
</div>

<script>
    var element = document.getElementById("canvas");

    if (element !== null) {
        google.charts.setOnLoadCallback(customerGroupDrawChart);
    }

    function customerGroupDrawChart() {
        var data = google.visualization.arrayToDataTable([
            ['Customer Group Name', 'Sales Qty'],
            <?php
            foreach ($customerGroupCollection as $group) {
                $customer_group_name = $group->getCustomerGroupCode();
                $customer_group_sales = $group->getCustomerGroupSales();

                echo "['" . $customer_group_name . "', " . $customer_group_sales . '],';
            }
            ?>
        ]);

        var options = {
            chartArea: {top:'5%', bottom: '5%'},
            colors: <?php echo $colors ?>,
            pieHole: 0.4,
        };

        var chart = new google.visualization.PieChart(document.getElementById('canvas'));

        chart.draw(data, options);
    }
</script>