<?php
/**
 * @category Qsolutions
 * @package Q_Admin
 * @author Michał Jóźwiak <michalj@qsolutionsstudio.com>
 *
 * @var $this Q_Admin_Block_Adminhtml_Customer_Tab_Graph
 */
?>

<?php
$registeredCustomer = $this->_registeredUsers;
$guestCustomer      = $this->_guestUsers;
$colors = $this->getDiagramHelper()->colorManipulator(2);
?>


<div class="box" id="customer_chart">
    <?php if ($guestCustomer !== floatval(0) && $guestCustomer !== null || $registeredCustomer !== floatval(0) && $registeredCustomer !== null): ?>
        <div class="only-chart" id="logged_canvas"></div>
    <?php elseif ($guestCustomer === floatval(0) && $registeredCustomer === floatval(0) || $guestCustomer === null && $registeredCustomer === null) : ?>
        <p class="a-center"><?php echo $this->__('No data found') ?></p>
    <?php endif; ?>
</div>

<script>
    var element = document.getElementById("logged_canvas");

    if (element !== null) {
        google.charts.setOnLoadCallback(loggedDrawChart);
    }

    function loggedDrawChart() {
        var data = google.visualization.arrayToDataTable([
            ['Customers', 'Sales Qty'],
            ['Guests User Group', <?php echo Mage::helper('core')->jsonEncode($guestCustomer); ?>],
            ['Registered User Group', <?php echo Mage::helper('core')->jsonEncode($registeredCustomer); ?>],
        ]);

        var options = {
            chartArea: {top:'5%', bottom: '5%'},
            colors: <?php echo $colors ?>,
            pieHole: 0.4,
        };

        var chart = new google.visualization.PieChart(document.getElementById('logged_canvas'));

        chart.draw(data, options);
    }
</script>